rebuild due to new macos host for osx-64
AnacondaRecipes/python-feedstock pull request #148
Opened 2024-07-18 17:25 UTC by rafaelmartins

{package} {version} {:snowflake:}

**Destination channel:** {Snowflake | defaults}

### Links

- [{ticket_number}]() 
- [Upstream repository]()
- [Upstream changelog/diff]()
- Relevant dependency PRs:
  - ...

### Explanation of changes:

- ...

2024-07-18 17:26 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_07a0curg0x/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:163: host_section_needs_exact_pinnings: output "python": Linked libraries host should have exact version pinnings.

===== ERRORS =====
- clone/recipe/meta.yaml:256: remove_python_pinning: On arch specific packages, python deps should not be constrained.
- clone/recipe/meta.yaml:277: missing_imports_or_run_test_py: output "libpython-static": Python packages require imports or a python test file in tests.
- clone/recipe/meta.yaml:258: remove_python_pinning: On arch specific packages, python deps should not be constrained.
- clone/recipe/meta.yaml:277: missing_tests: output "libpython-static": No tests were found.
===== Final Report: =====
4 Errors and 1 Warning were found

</details>

2024-07-18 19:40 UTC, cbouss approved these changes

2024-07-18 21:19 UTC, danpetry commented
@cbouss doesn't this need ac_sys_release to be updated?

2024-07-18 21:20 UTC, danpetry requested changes
see comment above

2024-07-18 21:22 UTC, cbouss commented
I think so

2024-07-18 21:27 UTC, danpetry approved these changes

2024-07-18 21:28 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_ec12mt0s22/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:163: host_section_needs_exact_pinnings: output "python": Linked libraries host should have exact version pinnings.

===== ERRORS =====
- clone/recipe/meta.yaml:277: missing_tests: output "libpython-static": No tests were found.
- clone/recipe/meta.yaml:256: remove_python_pinning: On arch specific packages, python deps should not be constrained.
- clone/recipe/meta.yaml:277: missing_imports_or_run_test_py: output "libpython-static": Python packages require imports or a python test file in tests.
- clone/recipe/meta.yaml:258: remove_python_pinning: On arch specific packages, python deps should not be constrained.
===== Final Report: =====
4 Errors and 1 Warning were found

</details>

2024-07-19 14:08 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_62qxq_1gta/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:163: host_section_needs_exact_pinnings: output "python": Linked libraries host should have exact version pinnings.

===== ERRORS =====
- clone/recipe/meta.yaml:256: remove_python_pinning: On arch specific packages, python deps should not be constrained.
- clone/recipe/meta.yaml:277: missing_imports_or_run_test_py: output "libpython-static": Python packages require imports or a python test file in tests.
- clone/recipe/meta.yaml:258: remove_python_pinning: On arch specific packages, python deps should not be constrained.
- clone/recipe/meta.yaml:277: missing_tests: output "libpython-static": No tests were found.
===== Final Report: =====
4 Errors and 1 Warning were found

</details>

2024-07-19 17:14 UTC, closed without merging