Adding instructions on how to test python
AnacondaRecipes/python-feedstock pull request #39
Opened 2021-07-28 19:33 UTC by remkade

Adds instructions to the README on how to validate that new python builds are working properly.

Not 100% sure this is the ideal place for this so let me know.

2021-07-28 19:58 UTC, chenghlee requested changes
I would put these sort of instructions in a separate file (e.g., `.anaconda/testing.md` or `README.anaconda.md`), rather than in the repo-level `README.md`. This will save us some headaches if/when we need to merge or PR against the upstream conda-forge feedstock.

2021-07-28 21:44 UTC, pseudoyim commented
I had this in my notes from when I last helped out with testing a python build:

- Create an env with the new `python` build coming specifically from `c3i_test` (other packages can come from defaults). For example:
 `conda create -n python388_test c3i_test2::python=3.8.8=*_5 conda-build; conda activate python388_test; python`
- Import some built-in modules (e.g. `math`, re, `crypt`)
- Successfully `conda-build` a package (e.g. tqdm-feedstock)
- Do this ^^ on all supported platforms.

2021-10-05 17:06 UTC, pseudoyim approved these changes
👍

2021-10-05 17:29 UTC, chenghlee approved these changes

2021-10-05 17:47 UTC, merged